# Generated by Django 4.0.10 on 2024-06-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ct_expansions', '0004_expansion_is_booster_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBlueprint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('yugioh_rarity', models.CharField(max_length=100)),
                ('collector_number', models.CharField(max_length=10)),
                ('first_ed', models.BooleanField(blank=True, null=True)),
                ('min_price_gbp', models.FloatField(blank=True, null=True)),
                ('min_price_gbp_formatted', models.CharField(blank=True, max_length=12, null=True)),
                ('image_download_link', models.CharField(blank=True, max_length=500, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct_expansions.expansion')),
            ],
        ),
    ]
