# Generated by Django 4.0.10 on 2024-06-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardblueprint',
            old_name='image_download_link',
            new_name='img_download_link',
        ),
    ]
