# Generated by Django 4.0.10 on 2024-06-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_cards', '0002_rename_image_download_link_cardblueprint_img_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardblueprint',
            name='min_price_gbp',
        ),
        migrations.RemoveField(
            model_name='cardblueprint',
            name='min_price_gbp_formatted',
        ),
        migrations.CreateModel(
            name='CardPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('min_price_gbp', models.FloatField(blank=True, null=True)),
                ('min_price_gbp_formatted', models.CharField(blank=True, max_length=12, null=True)),
                ('unlim_min_price_gbp', models.FloatField(blank=True, null=True)),
                ('unlim_min_price_gbp_formatted', models.CharField(blank=True, max_length=12, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct_cards.cardblueprint')),
            ],
        ),
    ]
