# Generated by Django 4.0.10 on 2024-06-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_cards', '0003_remove_cardblueprint_min_price_gbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricehistory',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 8)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cardpricehistory',
            unique_together={('card', 'date')},
        ),
    ]
