# Generated by Django 4.0.10 on 2024-05-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('card_link', models.URLField()),
                ('card_rarity', models.CharField(max_length=50)),
                ('card_code', models.CharField(max_length=20)),
                ('tcg_num_listings', models.IntegerField(null=True)),
                ('lore', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('card_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('simple_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('attribute', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('archtype', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('level', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('card_atk', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('card_def', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
        ),
    ]
