# Generated by Django 4.0.10 on 2024-05-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetSimulatedPriceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_mean', models.FloatField(blank=True, null=True)),
                ('booster_median', models.FloatField(blank=True, null=True)),
                ('chance_greater_opened_value', models.FloatField(blank=True, max_length=5, null=True)),
                ('date_simulated', models.DateField(blank=True, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
        ),
    ]
