# Generated by Django 4.0.10 on 2024-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_setsimulatedpricestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmittedSetPriceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_title', models.CharField(max_length=200)),
                ('simulated_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
