# Generated by Django 4.0.10 on 2024-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_usersubmittedsetprices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmittedsetprices',
            name='set_code',
            field=models.CharField(default='yugi', max_length=10),
            preserve_default=False,
        ),
    ]
