# Generated by Django 4.0.10 on 2024-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0005_usersubmittedsetprices_set_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedsetprices',
            name='set_code',
            field=models.CharField(choices=[('RA02', '25th Anniversary Rarity Collection II'), ('LEDE', 'Legacy of Destruction'), ('PHNI', 'Phantom Nightmare'), ('MZMI', 'Maze of Millennia'), ('VASM', 'Valiant Smashers'), ('RA01', '25th Anniversary Rarity Collection'), ('AGOV', 'Age of Overlord'), ('LD10', 'Legendary Duelists: Soulburning Volcano'), ('DUNE', 'Duelist Nexus'), ('BLMR', 'Battles of Legend: Monstrous Revenge'), ('WISU', 'Wild Survivors'), ('CYAC', 'Cyberstorm Access')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usersubmittedsetprices',
            name='set_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
