# Generated by Django 4.0.10 on 2024-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_alter_usersubmittedsetprices_set_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedsetprices',
            name='simulated_price',
            field=models.FloatField(max_length=10),
        ),
    ]
