# Generated by Django 4.0.10 on 2024-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0007_alter_usersubmittedsetprices_simulated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedsetprices',
            name='set_code',
            field=models.CharField(max_length=10),
        ),
    ]
