# Generated by Django 4.0.10 on 2024-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0008_alter_usersubmittedsetprices_set_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setsimulatedpricestats',
            old_name='booster_mean',
            new_name='booster_mean_marketp',
        ),
        migrations.RenameField(
            model_name='setsimulatedpricestats',
            old_name='booster_median',
            new_name='booster_mean_minlisting',
        ),
        migrations.RenameField(
            model_name='setsimulatedpricestats',
            old_name='chance_greater_opened_value',
            new_name='chance_greater_opened_value_marketp',
        ),
        migrations.AddField(
            model_name='setsimulatedpricestats',
            name='booster_median_marketp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setsimulatedpricestats',
            name='booster_median_minlisting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setsimulatedpricestats',
            name='chance_greater_opened_value_minlisting',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
