# Generated by Django 4.0.10 on 2024-05-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0009_rename_booster_mean_setsimulatedpricestats_booster_mean_marketp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateField()),
                ('mp_chance_today', models.FloatField()),
                ('mp_chance_change_week', models.FloatField(blank=True, null=True)),
                ('mp_chance_change_month', models.FloatField(blank=True, null=True)),
                ('ml_chance_today', models.FloatField()),
                ('ml_chance_change_week', models.FloatField(blank=True, null=True)),
                ('ml_chance_change_month', models.FloatField(blank=True, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
            options={
                'unique_together': {('set', 'ranking_date')},
            },
        ),
    ]
