# Generated by Django 4.0.10 on 2024-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0010_setrankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrankings',
            name='ml_chance_change_all_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setrankings',
            name='mp_chance_change_all_time',
            field=models.FloatField(default=0),
        ),
    ]
