# Generated by Django 4.0.10 on 2024-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0011_setrankings_ml_chance_change_all_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrankings',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setrankings',
            name='ml_chance_today',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
