# Generated by Django 4.0.10 on 2024-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0012_setrankings_ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setrankings',
            old_name='ranking',
            new_name='ml_ranking',
        ),
        migrations.AddField(
            model_name='setrankings',
            name='mp_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
