# Generated by Django 4.0.10 on 2024-05-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0013_rename_ranking_setrankings_ml_ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setrankings',
            old_name='ml_chance_change_all_time',
            new_name='ml_cgv_all_time',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='ml_chance_change_month',
            new_name='ml_cgv_change_week',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='ml_chance_change_week',
            new_name='ml_cgv_month',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='ml_chance_today',
            new_name='ml_cgv_today',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='mp_chance_change_month',
            new_name='mp_cgv_month',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='mp_chance_today',
            new_name='mp_cgv_today',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='mp_chance_change_week',
            new_name='mp_cgv_week',
        ),
        migrations.RenameField(
            model_name='setrankings',
            old_name='mp_chance_change_all_time',
            new_name='mp_cgvall_time',
        ),
    ]
