# Generated by Django 4.0.10 on 2024-05-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0014_rename_ml_chance_change_all_time_setrankings_ml_cgv_all_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setrankings',
            old_name='mp_cgvall_time',
            new_name='mp_cgv_all_time',
        ),
    ]
