# Generated by Django 4.0.10 on 2024-05-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0015_rename_mp_cgvall_time_setrankings_mp_cgv_all_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setrankings',
            old_name='ml_cgv_change_week',
            new_name='ml_cgv_week',
        ),
    ]
