# Generated by Django 4.0.10 on 2024-06-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0016_rename_ml_cgv_change_week_setrankings_ml_cgv_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='setsimulatedpricestats',
            name='booster_gainloss_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setsimulatedpricestats',
            name='booster_gainloss_mp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
