# Generated by Django 4.0.10 on 2024-06-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0017_setsimulatedpricestats_booster_gainloss_ml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetGainLossRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateField()),
                ('mp_gl_ranking', models.IntegerField(blank=True, null=True)),
                ('ml_gl_ranking', models.IntegerField(blank=True, null=True)),
                ('mp_gl_today', models.FloatField(blank=True, null=True)),
                ('mp_gl_week', models.FloatField(blank=True, null=True)),
                ('mp_gl_month', models.FloatField(blank=True, null=True)),
                ('mp_gl_all_time', models.FloatField(default=0)),
                ('ml_gl_today', models.FloatField(blank=True, null=True)),
                ('ml_gl_week', models.FloatField(blank=True, null=True)),
                ('ml_gl_month', models.FloatField(blank=True, null=True)),
                ('ml_gl_all_time', models.FloatField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
            options={
                'unique_together': {('set', 'ranking_date')},
            },
        ),
    ]
