# Generated by Django 4.0.10 on 2024-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0018_setgainlossranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrankings',
            name='ranking_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
