# Generated by Django 4.0.10 on 2024-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0020_rename_ranking_change_setrankings_ml_ranking_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setgainlossranking',
            name='ml_ranking_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setgainlossranking',
            name='mp_ranking_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
