# Generated by Django 4.0.10 on 2024-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='min_price_gbp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expansion',
            name='min_price_gbp_formatted',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
