# Generated by Django 4.0.10 on 2024-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0002_expansion_min_price_gbp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='bb_blueprint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
