# Generated by Django 4.0.10 on 2024-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0003_expansion_bb_blueprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='is_booster_box',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
