# Generated by Django 4.0.10 on 2024-06-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0004_expansion_is_booster_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpSimulatedPriceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_simulated', models.DateField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('gainloss', models.FloatField(blank=True, null=True)),
                ('cgv', models.FloatField(blank=True, max_length=5, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct_expansions.expansion')),
            ],
        ),
    ]
