# Generated by Django 4.0.10 on 2024-06-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0005_expsimulatedpricestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateField()),
                ('cgv_today', models.FloatField(blank=True, null=True)),
                ('cgv_week', models.FloatField(blank=True, null=True)),
                ('cgv_month', models.FloatField(blank=True, null=True)),
                ('cgv_all_time', models.FloatField(blank=True, null=True)),
                ('gainloss_today', models.FloatField(blank=True, null=True)),
                ('gainloss_week', models.FloatField(blank=True, null=True)),
                ('gainloss_month', models.FloatField(blank=True, null=True)),
                ('gainloss_all_time', models.FloatField(blank=True, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct_expansions.expansion')),
            ],
            options={
                'unique_together': {('expansion', 'ranking_date')},
            },
        ),
    ]
