# Generated by Django 4.0.10 on 2024-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_expansions', '0006_exprankings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exprankings',
            old_name='gainloss_all_time',
            new_name='gl_all_time',
        ),
        migrations.RenameField(
            model_name='exprankings',
            old_name='gainloss_month',
            new_name='gl_month',
        ),
        migrations.RenameField(
            model_name='exprankings',
            old_name='gainloss_today',
            new_name='gl_today',
        ),
        migrations.RenameField(
            model_name='exprankings',
            old_name='gainloss_week',
            new_name='gl_week',
        ),
        migrations.AddField(
            model_name='exprankings',
            name='cgv_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exprankings',
            name='cgv_ranking_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exprankings',
            name='gl_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exprankings',
            name='gl_ranking_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
