# Generated by Django 4.0.10 on 2024-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
    ]
